version: "3.9"

services:
  fastapi_app:
    container_name: fastapi_app
    image: fastapi_laliga:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/lib/app

